CREATE TABLE IF NOT EXISTS properties (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    listing_id TEXT,
    location TEXT,
    source_site TEXT,
    country TEXT,
    price TEXT,
    price_usd REAL,
    price_currency TEXT,
    property_type TEXT,
    bedrooms REAL,
    bathrooms REAL,
    toilet_rooms REAL,
    living_area TEXT,
    land_area TEXT,
    m2 REAL,
    rooms REAL,
    parking REAL,
    construction_year INTEGER,
    stratum INTEGER,
    is_project INTEGER,
    lat TEXT,
    lon TEXT,
    distance_to_coast_km REAL,
    elevation_m REAL,
    nearest_city_1k TEXT,
    distance_to_city_1k_km REAL,
    nearest_city_50k TEXT,
    distance_to_city_50k_km REAL,
    nearest_city_500k TEXT,
    distance_to_city_500k_km REAL,
    nearest_city_1mil TEXT,
    distance_to_city_1mil_km REAL,
    url TEXT UNIQUE,
    features TEXT,
    last_seen TIMESTAMP,
    scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);